---
title: "Publications"
---

## Journal Articles

### 2025

-   **Ahmed KY**, et. al,. Cardiometabolic Outcomes Among Adults With Abdominal Obesity and Normal Body Mass Index. JAMA Netw Open. 2025 Oct 1;8(10):e2537942.
-   **Ahmed KY**, et. al,. Normal-weight central obesity and cardiometabolic disorders among Aboriginal and Torres Strait Islander Australians. BMC Med. 2025 Feb 21;23(1):106.
-   Aychiluhm SB, Ross AG, Isaac V, Thapa S, **Ahmed K**Y. Central obesity and its association with youth physical and mental health: evidence from the Australian National Health Survey. BMC Med. 2025 Nov 26. 
-   Ross AG, ......, **Ahmed KY**. Diabetic kidney disease in rural Australia: prevention, management, treatment and way forward. Front Med (Lausanne). 2025 Jun 12;12:1561566.
-   Aychiluhm SB, Mondal UK, Isaac V, Ross AG, **Ahmed KY**. Interventions for Childhood Central Obesity: A Systematic Review and Meta-Analysis. JAMA Netw Open. 2025 Apr 1;8(4):e254331.
-   **Ahmed KY**, et. al.,. Population attributable fractions for modifiable risk factors of neonatal, infant, and under-five mortality in 48 low- and middle-income countries. J Glob Health. 2025 Jan 17;15:04015. 
-   Berhe FT, Shifti DM, Veerman JL, Aminde L, **Ahmed KY**, et al,. Digital versus nondigital behavioral interventions on cardiovascular risk reduction: systematic review and meta-analysis. Ann Behav Med. 2025 Jan 4;59(1):kaaf043.
-   Seid A, Cumpston MS, **Ahmed KY**, et. al,. The intergenerational association of preterm birth: A systematic review and meta-analysis. BJOG. 2025 Jan;132(1):18-26.
-   Kassa ZY, ....., **Ahmed KY**. Implementation, effectiveness, and barriers of obstetric triage in reducing waiting time: a scoping review. Reprod Health. 2025 Mar 21;22(1):43. 
-   Asresie MB, Ekholuenetale M, **Ahmed KY**, Mistry SK, Chandio N, Agho K, Fekadu GA, Arora A. Socioeconomic inequalities in high-risk fertility behaviors over time in Ethiopia. PLoS One. 2024 Dec 31;19(12):e0313028.
-   Kassa ZY, Dadi AF, Bizuayehu HM, Hassen TA, **Ahmed KY**, et al,. Person-centred maternity care during childbirth: a systematic review in low and middle-income countries. BMC Pregnancy Childbirth. 2025 Feb 12;25(1):147.
-   Astawesegn FH, **Ahmed KY**, et. al,. Limited Evidence to Fully Determine the Implementation of Evidence-Based Practice by Healthcare Providers in Africa: A Systematic Review and Meta-Analysis. J Evid Based Med. 2025 Jun;18(2):e70032.
-   Astawesegn FH, Naden P, Thapa S, **Ahmed KY**, et. al,. Inequities in mental health services among Aboriginal and Torres Strait Islander people in Australia. Public Health. 2025 Nov 26;250:106062.
-   Dadi AF, Hassen TA, Ketema DB, **Ahmed KY**, et. al,. Anxiety symptoms during pregnancy and risk of adverse birth outcomes in Gondar Town Ethiopia. Sci Rep. 2025 Oct 10;15(1):35475.
-   Ketema DB, ...., **Ahmed KY**. Socioeconomic inequality for hypertension among reproductive age women aged 15-49 from five Sub-Saharan Africa countries: A decomposition analysis of DHS Data. PLOS Glob Public Health. 2025 Jul 2;5(7):e0004738.
-   Giri S, Ross N, Kornhaber R, **Ahmed KY**, Thapa S. The effects of parental adverse childhood experiences (ACEs) and childhood threat and deprivation on adolescent depression and anxiety: an analysis of the longitudinal study of Australian children. Epidemiol Psychiatr Sci. 2025 Oct 6;34:e49.
-   Timilsina A, Chalise B, **Ahmed KY**, Thapa S. Effect of forest cover change on the prevalence of acute respiratory tract infections, diarrhoea, and fever among children under five: Using an ecosystem approach to child health. PLoS One. 2025 Aug 12;20(8):e0330101.  
